### ISSUE TITLE
Support randomly generated bridge usernames (required from Feb 2016)

### ISSUE THREAD

**Issue by haraldmartin** [Josef-Friedrich/Hue-shell#3]
I'll just refer to the official documentation from Philips regarding this:

http://www.developers.meethue.com/documentation/important-whitelist-changes

> Please be aware that in the coming months it will no longer be possible to create custom whitelist entries on the Hue bridge. The randomly generated bridge username must be used instead.
> It is anticipated this change will be rolled out to the public in February 2016.
> 
> This means that if you have developed a Hue Library or have a Hue app in the market which uses a custom whitelist username the bridge authentication will start failing after this date. So of course, if this is the case for your app/library it is strongly advised for you to update your app/library in the coming months to use the randomly generated bridge username.

**Comment by Josef-Friedrich** [comment]
Thank you for your note.

**Comment by Josef-Friedrich** [comment]
In `Hue shell` the username had to be configured manually. Therefore this library is not affected from the API change. The users simply have to put the randomly generated username in the corresponding configuration file, instead of a custom username.
