### ISSUE TITLE
sudo usage

### ISSUE THREAD

**Issue by baurmatt** [Josef-Friedrich/Hue-shell#8]
I haven't checked the whole script but i'm pretty sure this script doesn't necessarily need sudo. Could you please provide an option to enable/disable the usage of sudo?

**Comment by Josef-Friedrich** [comment]
`Hue-shell` uses sudo only in the installation script `install.sh`. The install script only uses `sudo`, if the command `sudo` is available on the target platform. Do you want to implement a `--sudo` option?
