### ISSUE TITLE
Problem bei Restart des Clients

### ISSUE THREAD

**Issue by mcl22** [Josef-Friedrich/Hue-shell#9]
Hi,

ich übersehe vermutlich etwas Grundlegendes, aber wenn ich den Raspberry auf dem hue-shell installiert ist neu starte, dann wechseln alle zu diesem Zeitpunkt eingeschalteten hue-Lampen die Farbe. Erst werden sie auf den Standard-warmweiß-Ton gestellt und wechseln dann ein wenig durch und schalten final (nachdem der Raspberry wieder hochgefahren ist) auf rot.

Was mache ich hier falsch bzw. was muss ich ändern um dieses Verhalten abzuschalten?

**Comment by Josef-Friedrich** [comment]
`Hue-shell` installiert automatisch ein paar Hintergrund-Dienste. Ich weiß, jetzt welches init System auf raspian verwendet wird, aber es werden systemd und sysvinit Dienste (je nachdem) gestartet. Vielleicht die zuerst einmal stoppen. Ich bin am überlegen, ob das so eine gute Idee ist diese Dienste überhaupt automatisch zu installieren.
